' <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
Imports System

Namespace Models
	Partial Public Class Person
		Public Property PersonId() As Integer
		Public Property LastName() As String
		Public Property FirstName() As String
		Public Property HireDate() As DateTime?
		Public Property EnrollmentDate() As DateTime?
		Public Property Discriminator() As String
	End Class
End Namespace